/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autobuyer;

import java.awt.AWTException;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Leo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        /*
        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                char letra = e.getKeyChar();
                System.out.println(letra);
                
            }
        });*/
        
        initComponents();
        setIcon();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        bTipo = new javax.swing.ButtonGroup();
        bConfusao = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tipo = new javax.swing.JLabel();
        rJog = new javax.swing.JRadioButton();
        rCons = new javax.swing.JRadioButton();
        botao = new javax.swing.JButton();
        pMinimo = new javax.swing.JLabel();
        pMaximo = new javax.swing.JLabel();
        txtPMin = new javax.swing.JTextField();
        txtPMax = new javax.swing.JTextField();
        confusao = new javax.swing.JLabel();
        rConfusaoS = new javax.swing.JRadioButton();
        rConfusaoN = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NextBuyer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        tipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipo.setText("Tipo");

        bTipo.add(rJog);
        rJog.setText("Jogador");
        rJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rJogActionPerformed(evt);
            }
        });

        bTipo.add(rCons);
        rCons.setText("Consumível");

        botao.setText("Concluído");
        botao.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                botaoComponentShown(evt);
            }
        });
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        pMinimo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pMinimo.setText("Preço venda mínimo");

        pMaximo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pMaximo.setText("Preço venda máximo");

        txtPMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPMinActionPerformed(evt);
            }
        });

        txtPMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPMaxActionPerformed(evt);
            }
        });

        confusao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confusao.setText("Gerar confusão");

        bConfusao.add(rConfusaoS);
        rConfusaoS.setText("Sim");
        rConfusaoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rConfusaoSActionPerformed(evt);
            }
        });

        bConfusao.add(rConfusaoN);
        rConfusaoN.setText("Não");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Caso queira mandar para a lista de transferência, deixe esses campos em branco.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Visa não parecer uma máquina, listando com preços mínimos diferentes.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confusao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rConfusaoS)
                        .addGap(18, 18, 18)
                        .addComponent(rConfusaoN))
                    .addComponent(tipo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rJog)
                        .addGap(18, 18, 18)
                        .addComponent(rCons))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pMinimo)
                            .addComponent(txtPMin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPMax, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMaximo)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rJog)
                    .addComponent(rCons))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pMinimo)
                    .addComponent(pMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(confusao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rConfusaoS)
                    .addComponent(rConfusaoN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(botao))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rConfusaoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rConfusaoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rConfusaoSActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed

        if(rConfusaoS.isSelected() == true){
            Jogador.setConfusao(true);
            Auto.setConfusao(true);
        } else if (rConfusaoN.isSelected()) {
            Jogador.setConfusao(false);
            Auto.setConfusao(false);
        }
        
        if(rJog.isSelected() == true) { // radio do jogador selecionado = verdade
            Auto.setTipo(true);
            Jogador.setPrecoMin(txtPMin.getText());
            Jogador.setPrecoMax(txtPMax.getText());
        } else if(rCons.isSelected() == true) { // radio do consumível selecionado = verdade
            Auto.setTipo(false);
            Auto.setItemMin(txtPMin.getText());
            Auto.setItemMax(txtPMax.getText());
        }
        
        if(txtPMax.getText().isEmpty() || txtPMin.getText().isEmpty()){
            Auto.setLista(true);
        }
        
        Auto.setFechar(true);
        
        try {
            Aplicacao.sortaNois();
        } catch (AWTException ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.exit(0);
        
    }//GEN-LAST:event_botaoActionPerformed

    private void txtPMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMinActionPerformed

    private void rJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rJogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rJogActionPerformed

    private void botaoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_botaoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoComponentShown

    private void txtPMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPMaxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bConfusao;
    private javax.swing.ButtonGroup bTipo;
    private javax.swing.JButton botao;
    private javax.swing.JLabel confusao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel pMaximo;
    private javax.swing.JLabel pMinimo;
    private javax.swing.JRadioButton rConfusaoN;
    private javax.swing.JRadioButton rConfusaoS;
    private javax.swing.JRadioButton rCons;
    private javax.swing.JRadioButton rJog;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField txtPMax;
    private javax.swing.JTextField txtPMin;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png"))); 
    }
}
